/**
 * Pipeline orchestration: fetch -> transform -> diagrams -> output.
 */

import {
  CodeWikiError, fetchWiki, normalizePayload, parseBatchExecute, parseRepoUrl,
} from './codewiki-client.js';
import {
  buildToc, collectHeadings, insertToc, linkifyReferences, normalizeAnchors,
  rewriteLinks, tidy,
} from './markdown.js';
import { transformDiagrams } from './diagrams.js';
import { splitDocument } from './split.js';

export { CodeWikiError, parseRepoUrl, parseBatchExecute, normalizePayload, fetchWiki };
export { dotToMermaid } from './dot-to-mermaid.js';

/**
 * Turn a fetched wiki into its final Markdown.
 *
 * Order matters: links and anchors are rewritten before diagrams so the
 * generated Mermaid is never scanned for Markdown syntax, and the table of
 * contents is built from the final heading text.
 */
export function buildDocument(wiki, {
  owner,
  repo,
  diagrams = 'mermaid',
  toc = true,
  diagramDir = 'diagrams',
} = {}) {
  const sourceUrl = `https://codewiki.google/github.com/${owner}/${repo}`;

  const linkOptions = { owner, repo, sha: wiki.sha };
  let md = rewriteLinks(wiki.markdown, linkOptions);
  md = linkifyReferences(md, linkOptions);
  md = normalizeAnchors(md);

  const diagramResult = transformDiagrams(md, {
    mode: diagrams,
    sections: wiki.sections,
    diagramDir,
  });
  md = diagramResult.markdown;

  if (toc) {
    md = insertToc(md, buildToc(collectHeadings(md)));
  }

  const header =
    `<!-- Generated by download-codewiki from ${sourceUrl}\n` +
    `     Repository commit: ${wiki.sha || 'unknown'} -->\n\n`;

  const body = tidy(md);
  return {
    markdown: header + body,
    body,
    files: diagramResult.files,
    diagrams: diagramResult,
    sourceUrl,
  };
}

/**
 * Build the split (multi-file) form of a document.
 *
 * Uses the body rather than the full document: the index page writes its own
 * title and provenance, so carrying the single-file header through would
 * duplicate both.
 */
export function buildSplit(document, wiki, { owner, repo }) {
  return splitDocument(document.body, {
    title: `CodeWiki: ${owner}/${repo}`,
    sourceUrl: document.sourceUrl,
    sha: wiki.sha,
  });
}
